repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/rvben/rumdl-pre-commit
    rev: v0.0.128
    hooks:
      - id: rumdl
        args: ["content", "--fix"]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        name: Run codespell to check for common misspellings in files
        language: python
        files: "content/posts/|content/pages/"
        types: [text]
        args: ["--write-changes", "--ignore-words", "spelling_wordlist.txt"]

  - repo: local
    hooks:
      - id: remove-gps-from-image-exif
        name: Remove GPS Info from image exif
        language: system
        pass_filenames: false
        entry: uv run inv check-and-remove-image-exif-gps-info
