from pelican.themes import attila

from scripts.build_story_database import view_config

HOST = "travlog.wei-lee.me"

# ----common between blogs----
PATH = "content"

# Blog Conf
AUTHOR = "Wei Lee"
SITEURL = "http://localhost:8000"
STATIC_SITEURL = SITEURL
SITELOGO = "/images/avatar.jpg"
BROWSER_COLOR = "#333333"
HEADER_COVER = "images/cover.jpeg"
SITE_DESCRIPTION = "動畫、電影、音樂、料理與旅遊的觀後感與生活紀錄"
SITESUBTITLE = SITE_DESCRIPTION
DEFAULT_DATE_FORMAT = "%Y/%m/%d - %a"
TIMEZONE = "Asia/Taipei"
SHOW_ARTICLE_MODIFIED_TIME = True

FAVICON = "favicon-32.png"
FAVICON_IE = "favicon.ico"
TOUCHICON = "apple-touch-icon.png"

# Page Setting
MAIN_MENU = True
DEFAULT_PAGINATION = 10
SHOW_PAGES_ON_MENU = False
SHOW_CATEGORIES_ON_MENU = False
SHOW_TAGS_IN_ARTICLE_SUMMARY = True
DIRECT_TEMPLATES = (
    "index",
    "categories",
    "archives",
    "tags",
    "series_list",
)
CATEGORIES_URL = "categories.html"
CATEGORIES_SAVE_AS = "categories.html"
ARCHIVES_URL = "archives.html"
ARCHIVES_SAVE_AS = "archives.html"
TAGS_URL = "tags.html"
TAGS_SAVE_AS = "tags.html"
SERIES_LIST_URL = "series_list.html"
SERIES_LIST_SAVE_AS = "series_list.html"

# This is a single-author site. Point author references at the about page instead
# of generating a second, paginated copy of the main article index.
AUTHOR_URL = "pages/about.html"
AUTHOR_SAVE_AS = ""

# Content Setting
ARTICLE_URL = "posts/{category}/{date:%Y}/{date:%m}/{slug}"
ARTICLE_SAVE_AS = "posts/{category}/{date:%Y}/{date:%m}/{slug}/index.html"
STATIC_PATHS = ["images", "extra", "static"]
EXTRA_PATH_METADATA = {
    "extra/robots.txt": {"path": "robots.txt"},
    "extra/favicon.ico": {"path": "favicon.ico"},
    "extra/favicon-16.png": {"path": "favicon-16.png"},
    "extra/favicon-32.png": {"path": "favicon-32.png"},
    "extra/favicon-512.png": {"path": "favicon-512.png"},
    "extra/apple-touch-icon.png": {"path": "apple-touch-icon.png"},
}

# License
CC_LICENSE = {
    "name": "創用 CC 姓名標示─相同方式分享",
    "version": "4.0",
    "slug": "by-sa",
}

# Feed generation is usually not desired when developing
FEED_ALL_ATOM = None
CATEGORY_FEED_ATOM = None
TRANSLATION_FEED_ATOM = None
AUTHOR_FEED_ATOM = None
AUTHOR_FEED_RSS = None

# Social widget
SOCIAL_PROFILE_LABEL = "保持聯繫"
SOCIAL = (
    ("Linkedin", "https://tw.linkedin.com/in/clleew"),
    ("GitHub", "https://github.com/Lee-W"),
    ("Twitter", "https://twitter.com/clleew"),
    ("RSS", f"https://{HOST}/feeds/all.atom.xml"),
)
JINJA_GLOBALS = {"POST_SHARE_MASTODON_DOMAIN": "g0v.social"}

# Markdown extension
MARKDOWN = {
    "extension_configs": {
        "markdown.extensions.admonition": {},
        "markdown.extensions.extra": {},
        "markdown.extensions.codehilite": {"css_class": "highlight"},
        "markdown.extensions.nl2br": {},
        "markdown.extensions.toc": {"toc_depth": "1-3"},
        "markdown_mermaidjs": {},
        "markdown_del_ins": {},
        "pymdownx.blocks.caption": {},
        "pymdownx.details": {},
        "pymdownx.snippets": {},
        "pymdownx.superfences": {},
        "pymdownx.tasklist": {},
    },
    "output_format": "html5",
}

# Utterance (comment system)
UTTERANCES_LABEL = "blog-comment"
COMMENTS_INTRO = '喜歡這篇文章的話，歡迎在下方留言（需要 GitHub 帳號），或是<a href="mailto:hello+travlog@wei-lee.me">寄 Email 找我聊聊！</a>'

# Theme Setting
THEME = attila.get_path()
THEME_TEMPLATES_OVERRIDES = ["theme-overrides"]
SITE_VARIANT = "travlog"
CSS_OVERRIDE = ("static/brand-travlog.css",)

# i18n
JINJA_ENVIRONMENT = {"extensions": ["jinja2.ext.i18n"]}
OG_LOCALE = "zh_TW"
DEFAULT_LANG = "zh-tw"
I18N_TEMPLATES_LANG = "en"
LANGUAGES = (
    ("zh-tw", "/"),
    ("ja", "/ja/"),
)
LANGUAGE_NAMES = {"zh-tw": "臺灣華語", "ja": "日本語"}
CURRENT_LANG = "zh-tw"
I18N_SUBSITES = {
    "ja": {
        "RANDOM_ARTICLE_FALLBACK_URL": "/random/",
        "SITENAME": "誰も気にしないこと",
        "SITETITLE": "誰も気にしないこと",
        "SITE_DESCRIPTION": "アニメ・映画・音楽・料理・旅行の感想と暮らしの記録",
        "SITESUBTITLE": "アニメ・映画・音楽・料理・旅行の感想と暮らしの記録",
        "OG_LOCALE": "ja_JP",
        # Reuse the main site's theme assets instead of the plugin's
        # relative default ("../theme"), which renders as SITEURL/../theme/.
        "THEME_STATIC_DIR": "theme",
        "THEME_STATIC_PATHS": [],
        # The plugin defaults subsites to STATIC_PATHS = [], which leaves the
        # favicons and brand-travlog.css (it styles .rights-notice) 404 under
        # /ja/. Copy those two small dirs; images stay on the main site.
        "STATIC_PATHS": ["extra", "static"],
        # Generated by scripts/build_ja_data.py at build time. The two
        # plugins resolve their roots differently: tabular against this
        # config file, pelican-osm against PATH (content/).
        "TABULAR_DATA_ROOT": ".ja-data",
        "OSM_PLACES_ROOT": "../.ja-data/places",
        # Articles are not generated here (I18N_UNTRANSLATED_ARTICLES), so the
        # links to them from the data pages point back at the main site.
        # This stays relative in production: Pelican prefixes the subsite URL.
        "ARTICLE_LANG_URL": f"../{ARTICLE_URL}",
        "ARTICLE_LANG_SAVE_AS": "",
        "CATEGORY_TRANSLATIONS": {
            "Cook": "料理",
            "Review": "レビュー",
            "Travel": "旅行",
        },
        "MENUITEMS": (
            ("🏠 ホーム", "/ja/"),
            ("🙋 このサイトについて", "/ja/pages/about.html"),
            ("🗝️ コレクション", "/ja/pages/pages.html"),
            (
                "🧭 さがす",
                (
                    ("📜 ブログロール", "/ja/pages/blogroll.html"),
                    ("©️ 著作権", "/ja/pages/copyright.html"),
                    ("🔒 プライバシー", "/ja/pages/privacy.html"),
                ),
            ),
            ("🎲 ランダム", "/ja/random/"),
        ),
    }
}
I18N_UNTRANSLATED_ARTICLES = "remove"
I18N_UNTRANSLATED_PAGES = "keep"

# Plugin-setting
PLUGINS = [
    "pelican.plugins.i18n_subsites",
    "pelican.plugins.neighbors",
    "pelican.plugins.render_math",
    "pelican.plugins.seo",
    "pelican.plugins.sitemap",
    "pelican.plugins.series",
    "pelican.plugins.share_post",
    "pelican.plugins.statistics",
    "pelican.plugins.summary_link",
    "pelican.plugins.tag_cloud",
    "pelican.plugins.webassets",
    "pelican.plugins.heatmap",
    "pelican.plugins.osm",
    "pelican.plugins.tabular",
    "pelican.plugins.on_this_day",
    "pelican.themes.attila.readtime",
    "pelican.plugins.stat",
]
PAGEFIND_ENABLED = True
RANDOM_ARTICLE_BUTTON = True
SUMMARY_LINK_FORMAT = ""
SITEMAP = {
    "format": "xml",
    "changefreqs": {
        "articles": "monthly",
        "pages": "monthly",
        "indexes": "weekly",
    },
}

# Local plugins
LOCAL_PLUGINS = [
    "random_article_subsites",
    "image_markup",
]
PLUGIN_PATHS = ["plugins"]
PLUGINS.extend(LOCAL_PLUGINS)
# pelican-tabular settings
#
# 資料列的 <field>_ref 欄位（例如 content/data/concerts.yaml 的 venue_ref）
# 會去 content/places/ 取那筆地點，連結由下面的 fallback chain 產生：
# 有 osm_type/osm_id 就直接指到 OpenStreetMap 上那個實體（穩定、改名或
# 修地址後仍對得上），沒有才退回座標形式。座標形式用 ?mlat=&mlon= 而非
# 單純的 #map= 置中，前者會放一個圖釘，後者只會把地圖移過去、讀者還是
# 不知道指的是哪一棟。兩者都缺就不給連結，只顯示純文字。
TABULAR_REF_HREF_TEMPLATE = (
    "https://www.openstreetmap.org/{osm_type}/{osm_id}"
    "|https://www.openstreetmap.org/?mlat={lat}&mlon={lon}#map=17/{lat}/{lon}"
)

# One view for both languages: pelican-tabular resolves labels, messages and
# the translated `title` from the component's language (the page's `Lang`).
TABULAR_VIEWS = {"works": view_config()}

# pelican-seo settings
SEO_REPORT = True  # SEO report is enabled by default
SEO_ENHANCER = False
SEO_ENHANCER_OPEN_GRAPH = False
SEO_ENHANCER_TWITTER_CARDS = False


# ----this blog only----
# Blog Conf
SITENAME = "那些沒人在乎的事"
SITETITLE = SITENAME

# Utterance (comment system)
UTTERANCES_REPO = "Lee-W/travlog"

# Page Setting
MENUITEMS = (
    ("🏠 首頁", "/"),
    ("🙋 關於", "/pages/about.html"),
    ("🗝️ 私藏", "/pages/pages.html"),
    (
        "📂 分類",
        (
            ("🍿 評論", "/category/review.html"),
            ("✈️ 旅遊", "/category/travel.html"),
            ("🥘 料理", "/category/cook.html"),
        ),
    ),
    (
        "🧭 探索",
        (
            ("🏷️ 標籤", "/tags.html"),
            ("🗄️ 歸檔", "/archives.html"),
            ("📚 系列文章", "/series_list.html"),
            ("📜 部落卷", "/pages/blogroll.html"),
            ("©️ 著作權", "/pages/copyright.html"),
            ("🔒 隱私權", "/pages/privacy.html"),
        ),
    ),
    ("🎲 隨機", "/random/index.html"),
)

# Content Setting
DEFAULT_CATEGORY = "Travel"

# Theme Setting
PYGMENTS_STYLE = "default"
AUTHOR_META = {
    "Wei Lee": {
        "image": "/images/avatar.jpg",
    }
}

# Category labels
CATEGORY_TRANSLATIONS = {
    "Cook": "料理",
    "Review": "評論",
    "Travel": "旅遊",
}
